# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0002_auto_20160201_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeingModeltoForeingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_name', models.CharField(choices=[(b'a', b'1'), (b'b', b'2'), (b'c', b'3')], help_text=b'write something', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='big_integer_field',
            field=models.BigIntegerField(blank=True, help_text=b'An big integer field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='binary_field',
            field=models.BinaryField(blank=True, help_text=b'A binary field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='char_field',
            field=models.CharField(blank=True, help_text=b'write something', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='comma_separated_integer_field',
            field=models.CommaSeparatedIntegerField(blank=True, help_text=b'A comma sepparated integer field', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='date_field',
            field=models.DateField(blank=True, help_text=b'A date field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='datetime_field',
            field=models.DateTimeField(blank=True, help_text=b'A datetime field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='decimal_field',
            field=models.DecimalField(blank=True, decimal_places=10, help_text=b'A decimal field', max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='duration_field',
            field=models.DurationField(blank=True, help_text=b'A duration field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='email_field',
            field=models.EmailField(blank=True, help_text=b'A email field', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='file_field',
            field=models.FileField(blank=True, help_text=b'A file field', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='file_path_field',
            field=models.FilePathField(blank=True, help_text=b'A file path field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='float_field',
            field=models.FloatField(blank=True, help_text=b'A float field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='generic_ip_addr_field',
            field=models.GenericIPAddressField(blank=True, help_text=b'A generic ip addr field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='image_field',
            field=models.ImageField(blank=True, help_text=b'A image field', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='int_field',
            field=models.IntegerField(blank=True, help_text=b'Put a number, magic number', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='many_to_many_field',
            field=models.ManyToManyField(blank=True, help_text=b'A many to many field', null=True, to='second_app.ManyToManyModel'),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='positive_integer_field',
            field=models.PositiveIntegerField(blank=True, help_text=b'A positive integer', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='positive_small_integer_field',
            field=models.PositiveSmallIntegerField(blank=True, help_text=b'A positive small integer field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='slug_field',
            field=models.SlugField(blank=True, help_text=b'A slug field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='small_integer_field',
            field=models.SmallIntegerField(blank=True, help_text=b'A small integer field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='text_field',
            field=models.TextField(blank=True, help_text=b'Put a large test here', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='time_field',
            field=models.TimeField(blank=True, help_text=b'A time field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='url_field',
            field=models.URLField(blank=True, help_text=b'A url field', null=True),
        ),
        migrations.AlterField(
            model_name='allfieldsmodel',
            name='uuid_field',
            field=models.UUIDField(blank=True, help_text=b'A uuid field', null=True),
        ),
        migrations.AlterField(
            model_name='foreingmodel',
            name='name',
            field=models.CharField(choices=[(b'a', b'1'), (b'b', b'2'), (b'c', b'3')], help_text=b'write something', max_length=500),
        ),
        migrations.AddField(
            model_name='foreingmodeltoforeingmodel',
            name='foreign_key_field',
            field=models.ForeignKey(help_text=b'A foreign_key field', on_delete=django.db.models.deletion.CASCADE, to='second_app.AllFieldsModel'),
        ),
    ]
