# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second_app', '0003_auto_20160217_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreingmodeltoforeingmodel',
            name='foreign_key_field',
            field=models.ForeignKey(help_text=b'A foreign_key field', on_delete=django.db.models.deletion.CASCADE, to='second_app.ForeingModel'),
        ),
    ]
